### ISSUE TITLE
Extras no longer show

### ISSUE THREAD

**Issue by crywolf203** [contrary-cat/LocalTVExtras.bundle#16]
Plex web version: Version 4.64.3 
With the new version of plex, the Extras no longer show with this bundle. Now I see trailers from plex.

**Comment by contrary-cat** [comment]
I'm still seeing extras in the latest Plex Web myself, and they're still being added correctly in the latest version of Plex Media Server (although removing extras is buggy now, and doesn't seem to be fixable). Do you know whether the problem is with Plex Web not displaying your extras, or them not being added to the database properly? This agent would only affect the latter.

If you're able to switch over to their new Plex TV Series agent (upgrade matching on your library), then that now automatically adds local extras at show, season and episode level. I think titles for the episode extras is the only thing missing compared to this agent. It will probably be more reliable in the long run, since it's officially supported.

**Comment by jpschewe** [comment]
I tried switching to "Plex TV Series" and I didn't see any extras. I went back into the settings and clicked "Find Extras" and the settings can't be saved. I see Plex Pass required next to this, but assumed this is for finding extras on the Internet. Is it the case that viewing extras saved on disk requires Plex Pass?

**Comment by contrary-cat** [comment]
The Plex TV Series doesn't support 3rd party agents, so I'm not able to help with what's going on there.

Here's their help page for local extras: https://support.plex.tv/articles/local-files-for-tv-show-trailers-and-extras/

Plex Pass is only required for the internet extras, local extras are available for everyone.

Since the new method was created and is supported by the Plex team, you can ask them for help on the forum https://forums.plex.tv

**Comment by jpschewe** [comment]
For others that may run across this, the fix is at https://forums.plex.tv/t/cant-save-library-settings-episodes-not-scanned-in/740581

**Comment by aaronsmith203** [comment]
Hey This works but I am not sure if its Plex or the add on. When I Change the "Extras" folders to "Featurettes" , everything works just as expected. I always keep my plex up to date and also mostly run the betas.
