### ISSUE TITLE
Not Recognizing extras

### ISSUE THREAD

**Issue by DevXen** [contrary-cat/LocalTVExtras.bundle#3]
Doesn't appear to be identifying Extras. I'd assume because of my season folder names but i'm not sure. I've added pics of my folders/files in the test show I was testing with. as well as the plex webapp for that series, and the  agent settings. 

I'm using Windows 10. lastest Plex server.

Looking at the logs it did add an extra to a difference series. though only the 1 I was able to tell. and that extra is in an [Extras] folder. has doesn't have any of the inline identifiers. so that's strange. but you'll see that in the log. 

![12 Monkeys Deleted Scenes Folder (Testing for LocalTVExtras Plugin)](https://user-images.githubusercontent.com/2284801/55277651-43721e80-52c8-11e9-87f4-63792ecadb45.png)
![12 Monkeys Folder (Testing for LocalTVExtras Plugin)](https://user-images.githubusercontent.com/2284801/55277652-43721e80-52c8-11e9-8f6e-af78495e8a0e.png)
![12 Monkeys Other Folder (Testing for LocalTVExtras Plugin)](https://user-images.githubusercontent.com/2284801/55277653-43721e80-52c8-11e9-946c-377cac2061ef.png)
![12 Monkeys Specials - Webisodes Folder (Testing for LocalTVExtras Plugin)](https://user-images.githubusercontent.com/2284801/55277654-43721e80-52c8-11e9-82fe-83435a859603.png)
![12 Monkeys Trailers Folder (Testing for LocalTVExtras Plugin)](https://user-images.githubusercontent.com/2284801/55277655-440ab500-52c8-11e9-8d04-867406d7f6c5.png)
![Plex 12 Monkeys Page (Testing for LocalTVExtras Plugin)](https://user-images.githubusercontent.com/2284801/55277656-440ab500-52c8-11e9-860a-e37d8e967c50.png)
![Plex Agents List (Testing for LocalTVExtras Plugin)](https://user-images.githubusercontent.com/2284801/55277657-440ab500-52c8-11e9-90d2-3ceae4592c4b.png)

Apparently GitHub doesn't support XML Files. so I had to rename it to .txt.

[com.plexapp.agents.localtvextras.log](https://github.com/contrary-cat/LocalTVExtras.bundle/files/3025582/com.plexapp.agents.localtvextras.log)

[com.plexapp.agents.localtvextras.xml.txt](https://github.com/contrary-cat/LocalTVExtras.bundle/files/3025581/com.plexapp.agents.localtvextras.xml.txt)

**Comment by contrary-cat** [comment]
Thanks for the uploads, the log doesn't actually show a metadata refresh though, perhaps the server was restarted?

Can you refresh metadata on that show, and then see if there's any additional information in the log?

**Comment by DevXen** [comment]
Yeah, I think either the Refresh may not of finished before I attached it, I swear it had though. (I Checked by going to the menu and waited for it to be available to click again.). or maybe cause it had 6 Log files. and so I sent the one that seemed to be updated/changed by the Last motified date/time.

So I just got home. and checked the 12 monkeys for the hell of it. and it had Most of the extras. just not the Webisodes. but I'm sure that's cause they are in a s [Webisodes] sub folder. under [Specials]

I haven't tried to add the brackets to my 'Identifier folders' yet. So I'll try that and see how it goes. But so far so good. - 

I also have a suggestion. I'm not sure if there's a section for that. What about adding new identifier folders, if it's possible to add extras. or maybe even a way to add our own as needed. Like for example: Webisodes, Inside The Episodes (Which I guess is kind of like Behind the scenes), and Talking shows/after show specials. like: Anarchy Afterword. is listed as specials in TheTVDB. but Talking bad is listed as it's own Separate show. When they would Probably be better as extras for the show. Especially when they are episode specific. Anyways, just a couple ideas. - Thanks!


-Dev

**Comment by DevXen** [comment]
okay adding Brackets. refreshing metadata and scanning the files. the files are still listed, but are unplayable. - as the folder was moved. I'll try again when I wake up tomorrow. i'll try restarting the server. deleting the current localextras.log files refreshing the metadata and scanning the files. and empty trash. to see if that helps at all.

**Comment by contrary-cat** [comment]
I'm glad it's now working for you. And you're correct that the webisodes won't be found, both because they are in a [Specials] folder (specials isn't one of the defined extra folder names in the agent because it clashes with the plex episode structure), and because of being in a subfolder.

For extras, Plex will only support the limited set of behind the scenes, deleted scene, featurette, interview, scene, short, trailer and other. Unfortunately it isn't possible to define custom types to be imported, that is why I import files located in the "Extras" folder as the other extra type.

However I'll keep the feature request in mind, since it may not be too complicated to implement additional or custom aliases for folder types if there's a demand for that. e.g. perhaps webisode could be imported as short.

I should note that the scanning is probably quicker if you don't have the "Assign Extras to Episodes..." setting enabled, since that setting does involve a number of duplicate folder scans. I'm trying to work on making it more efficient, but at only a few hours per week, that will take some time.  If you do need episode extras, and have a lot to add, then give it plenty of time to scan through all the files (especially if your show has a lot of episodes).

P.S. Have just seen your update - media scan not necessary, nor is empty trash (also unlikely to work). Just refresh metadata on the TV show, and wait for it to update. Extras will disappear and be re-added, it may take some time.

**Comment by DevXen** [comment]
Yeah i just checked from my phone.  The refresh metadata on under series is no longer greyed out so I would guess it's done. Still listed. And not playing. Though i do still have [ in the alternate folder names. But it is still doing the media scan so maybe that's why it hasn't updated the file data yet. Hmm. 


![Screenshot_20190331-010450_Chrome](https://user-images.githubusercontent.com/2284801/55285901-80cebe80-5351-11e9-8daa-259f38b8a2ad.jpg)
![Screenshot_20190331-010459_Chrome](https://user-images.githubusercontent.com/2284801/55285904-8c21ea00-5351-11e9-9891-ce12ac092ebb.jpg)
![Screenshot_20190331-010518_Chrome](https://user-images.githubusercontent.com/2284801/55285905-92b06180-5351-11e9-9b4f-ccbb38cdfad6.jpg)

**Comment by DevXen** [comment]
Okee. I just woke up and checked. The extras are there and working. My bird is the scan for files needed to finish I dunno. Thank you for all your help.  This is going to save me soon much time. And it's a better layout then having them all as specials. Now I just need to find a program to generate thumbnails. Since plex apparently won't for them.

**Comment by contrary-cat** [comment]
This seems to be an issue with Plex 1.15 [https://forums.plex.tv/search?q=thumbnails%20extras%201.15](https://forums.plex.tv/search?q=thumbnails%20extras%201.15), so hopefully they'll figure it out soon. You can fix it by either temporarily downgrading to 1.14 (the thumbnails will still be present after upgrading again), or by adding inline thumbnails (e.g. a jpg with the same file name as your extra video). There are a few ffmpeg commands you could use to generate thumbnails if you don't have images to hand.

The bad news is that Plex won't allow you to change the image in an extra unless it is being freshly added to the database. If you're doing this for a lot of files, then the best way is probably to disable the agent, refresh metadata to remove all of the extras, then enable the agent and refresh metadata again to add them. So you'll have to go through the long wait again to update them.

**Comment by DevXen** [comment]
I was able to downgrade to 1.14. Thank you for that advice. I didn't even know that was possible without creating new libraries. - I figure it'd be easier to let Plex create the thumbnails than to manually add them for hundreds of files. 

So far things seem to be working great. I am curious though. is it possible to put the extra folders inside a sub folder.  i.e.: [Extras]\[Behind The Scenes], [Extras]\[Other]? I haven't been doing that. but if it'll still add them. that would be much better to organize the folders on the HDD.

**Comment by contrary-cat** [comment]
No, that isn't possible, I've chosen to keep the location of the extras consistent with what Plex does for movies. If you wanted to change to a different structure, then you would have to fork the agent and alter the code.

Since it seems to be working for you now, I'll close the issue. Hope you enjoy your extras.

**Comment by DevXen** [comment]
Okee. Sounds good. Thank you for all your help.
