### ISSUE TITLE
Only seeing extras for a few shows

### ISSUE THREAD

**Issue by gw2** [contrary-cat/LocalTVExtras.bundle#4]
I've got extras without thumbnails for a few shows (honestly the manual thumbnails are enough for me if i can get extras to show) but the scanner seems to find all the other extras, but either not add them, or they are not displaying. I've been at this 2 days now, reinstalled plex server go to older versions (saw meniton of 1.14 in a previous issue thread), disabled and refreshed all metadata, then enabled and refreshed all metadata, it seems to only add extras for the first 2 or 3 shows. I do have the option checked to show folders at the episode, season, and show levels.

My Plex folder structure is 
TV:
D:\Media\TV\DVD\
![image](https://user-images.githubusercontent.com/3276372/55696754-69648680-598c-11e9-90c0-3b228f33829f.png)
D:\Media\TV\Bluray Rips\
![image](https://user-images.githubusercontent.com/3276372/55696789-8ef19000-598c-11e9-99ca-571972957d7f.png)

The only 2 shows I can find extras listed for are Baccano! and Beast Wars, so 1 from DVD and 1 from Bluray, so i dont think having seperate folders is an issue.

Here are some example show folders

Desert Punk - working
Show has only 1 season - ie just a show folder
- has an Extras subfolder with named MKV files
- originally i had thought the issue was inline not working for i removed the suffix's from everything and moved all extras into extras folders for each show
![image](https://user-images.githubusercontent.com/3276372/55696885-02939d00-598d-11e9-9a32-7362e5913041.png)
![image](https://user-images.githubusercontent.com/3276372/55696984-65853400-598d-11e9-82d5-4df87fe5e48c.png)

Beast Wars - working
Show w/ seasons - Extras at show level:
![image](https://user-images.githubusercontent.com/3276372/55696687-20accd80-598c-11e9-9ffc-24d3e3cfc3db.png)
![image](https://user-images.githubusercontent.com/3276372/55696720-4639d700-598c-11e9-8b3a-bdbad7d5d10a.png)
- Extras show just like in desert punk above, no need for a screenshot here

Baccano! - working
Show folder only w/ inline extras
![image](https://user-images.githubusercontent.com/3276372/55697057-bdbc3600-598d-11e9-8e8e-ff371273b37f.png)
- Extras show just like in desert punk, no screenshot needed

The Big Bang Theory - not working
Show w/ 9 season folders - Extras folder in each season folder
- other shows with this issue i have are criminal minds (11 seasons), Black Lagoon (2 seasons, 1 specials season, specials has extras subfolder as does season 2), Breaking Bad (2 sersons), yada yada)
![image](https://user-images.githubusercontent.com/3276372/55697287-c06b5b00-598e-11e9-8231-db376e362383.png)
![image](https://user-images.githubusercontent.com/3276372/55697280-b0537b80-598e-11e9-9b76-f77a42148743.png)

I was mainly focusing on going in order, so i have been trying to get them to show on big bang theory. here is the log from the plugin

[com.plexapp.agents.localtvextras.log](https://github.com/contrary-cat/LocalTVExtras.bundle/files/3052532/com.plexapp.agents.localtvextras.log)

[com.plexapp.agents.localtvextras.1.log](https://github.com/contrary-cat/LocalTVExtras.bundle/files/3052533/com.plexapp.agents.localtvextras.1.log)

Any guidance at all would be greatly appreciated, if you need any more information i will be happy to provide it. Thank you again for this wonderful plugin, I can;t for the life of me understand why plex has ignored this for so long.

**Comment by contrary-cat** [comment]
As far as I can tell, the ones you have working are those where the extras are in the show folder, while the ones that aren't have the extras in the season folder. I think the reason for this is that Plex Web only shows extras at the show level, so while they can be added to the server, they won't be shown on the web client.

I wouldn't recommend attaching extras to seasons unless you have a client that supports that, but if you do, and just want to save some time then you can also check if they are there by inspecting the xml file:

You can get the template for the xml url by going to any episode, and selecting Get Info > View XML

This XML url will be something like https://[unique subdomain].plex.direct:32400/library/metadata/[id of the episode]?checkFiles=1&includeExtras=1&includeBandwidths=1&X-Plex-Token=[your plex token]

You can then get the season id from the URL of the season in the Plex Web client, the end should look something like this:
?key=%2Flibrary%2Fmetadata%2F[id of the season]

So if you replace [id of the episdode] in the XML with [id of the season], then you'll see the XML details that Plex has on that season. (If you know any javascript, you can turn this procedure into a bookmarklet for your preferred browser).

If your extras have been attached correctly, then you will see them listed within the <Extras> tag, e.g. for The Big Bang Theory season 1, this would be <Extras size="2"> with a <Video> child for each extra. You still need a client with full support to play them, but it's the quickest way I've found to check that they are there.

I'm sorry it isn't easier on the web client, I have [put in my request for them to expand extras to seasons and episodes there](https://forums.plex.tv/t/tv-series-dvd-special-features-extras-behind-the-scenes-interviews-trailers-etc/177179/24), and hopefully that is something they will act on sooner rather than later.

**Comment by gw2** [comment]
I see, i had thought the web client supported Extras at every level, my mistake. Thank you for clarifying this, I think I'll just prefix the extras with their season number and put them at the show level. I had already voted for that request apparently so I guess that's all I can do there.

Thanks again for the great work you've done here.
