### ISSUE TITLE
Plugin Not Detected

### ISSUE THREAD

**Issue by LanceMcCarthy** [contrary-cat/LocalTVExtras.bundle#6]
Using latest Plex Server `1.15.6.1079` on Windows 10 (1903), I dropped the unzipped and unblocked bundle  `LocalTVExtras.bundle` into the server's plugins folder (next to Services.bundle).

Just to make sure, I checked off the "Disable capability checking" setting in case that was a problem.

Did I make a noob mistake? Am I supposed to restart the server or some other trick to load up plugins??

**Comment by contrary-cat** [comment]
First, double-check that you're adding it to the user plug-in folder. I don't use plex on windows myself, but you should be able to find it in `%LOCALAPPDATA%\Plex Media Server\Plug-ins` (if the Plug-ins directory doesn't already exist in `%LOCALAPPDATA%\Plex Media Server\`, then create it before adding the agent).

I usually find that Plex finds new agents without restarting. But if "Local TV Extras Agent" doesn't show up in the list of agents when you go to **Settings > Agents > Shows > Personal Media/TVDB/The Movie Database**, then I would suggest a server restart as the next step since that is one way of forcing the server to check what agents have been added.

**Comment by LanceMcCarthy** [comment]
thanks for the prompt reply @contrary-cat !

My problem was that I was looking for the plugin in the **Settings > Plugins** menu :) Once I went to the **Settings > Agents** list, it was there.

Once there, I noticed that it wasn't enabled for any menu, here's a screenshot of what it appears as:

![image](https://user-images.githubusercontent.com/3520532/58430293-c4eeee80-8076-11e9-83a3-4dd55a0b328e.png)

Should I enable it for all the categories? 

- Personal Media Shows
- TheTVDB
- The Movie Database

**Comment by LanceMcCarthy** [comment]
OMG This works amazing. Thanks for sharing!

I'm primarily a .NET dev, but I do play around with Python for machine learning. Now that I know I can write scanners in Python, I'm going to have a ton of fun with this! Are there API docs that I can use, or is this a "learn as you break stuff" kind of thing?

**Comment by contrary-cat** [comment]
I'm glad it's working for you. In answer to your earlier question: all three is probably the most likely to work all the time. The TVDB is the Plex default for matching shows, so you might be able to get away with just that, but if you ever Fix Match and choose a different source, then it would need to be enabled for that agent too.

There aren't any API docs that I have found, the agents that I have made were figured out partly through reading the code in other agents (you can find some [here](https://github.com/plexinc-agents), and even more in the forums) and also some trial and error. A lot of printing things to the logs at first, but once things start to come together it's really cool.
