### ISSUE TITLE
If a special is in the root - no extras

### ISSUE THREAD

**Issue by nopoz** [contrary-cat/LocalTVExtras.bundle#7]
I had a show where all the seasons were neatly sorted into their "Show/Season XX" folders. There was one stray file that was in in the show root folder like this "Show/Show S00E04.mkv". With this stray file there, extras would not be added no matter what. Once I moved this stray file into it's "Show/Season 00" folder, extras were added on re-scan as expected.

**Comment by contrary-cat** [comment]
To help me reproduce the issue and see what the problem is, could you give me a minimal example where the problem occurs, including the location of the extra files?

The way the agent currently works is that it decides if your episode is saved in a season folder, or directly in the show folder

If it is in the show folder, then it will search for extras, along these lines:
* Anything in Show/ named Title-extra_type.ext
* All video files in Show/extra_type/ 

(Where extra_type is one of the words that are mentioned in the README)

If your extras follow that convention, and were in the show folder, then they should have been found either way.

If your extras were in one of the season folders, then (assuming everything is working OK) the only reason for them to be absent is if there weren't any episodes at all in the season folder in question.
