### ISSUE TITLE
Extras fail to populate, depending on the name of the show directory

### ISSUE THREAD

**Issue by mikansoro** [contrary-cat/LocalTVExtras.bundle#9]
### Issue Description:
I came across an issue in the most recent build of the agent (perhaps it's existed for a while, I just started using it), that causes extras to fail to be added to plex depending on the directory name of the show directory. I have only managed to make it happen to one directoy name in particular, but it is repeatable, hence this issue.

[AniDB for Mirai no Mirai](https://anidb.net/anime/13174)

### Replication Steps: 
If the show directory is named `Mirai no Mirai`, extras will fail to appear on a metadata refresh, and will disappear if they are currently displayed.

If the show directory is named `Mirai`, the extras will appear/reappear on a metadata refresh and play properly. 

### Other Agents/Notes

- This library is configured to use the Absolute Series Scanner, and the HamaTV agent. Mirai is a movie, however due to the nature of HamaTV's anime support and the nature of AniDB, movies are treated as shows in this library.
- Plex is configured to hide the "Season" screen if there is only one season found.

### Screenshots
(These are taken from a windows machine with a mapped drive, the log is from Plex running on macos using a mapped SMB share)

Show Directory: 
![image](https://user-images.githubusercontent.com/41764397/72864625-506a5f00-3c9a-11ea-9a36-973c8bbdb9c7.png)

Trailers Directory: 
![image](https://user-images.githubusercontent.com/41764397/72864704-8ad3fc00-3c9a-11ea-8dd4-b3dbeb131307.png)

Plex (Working, when show directory is named `Mirai`): 
![image](https://user-images.githubusercontent.com/41764397/72864726-a4754380-3c9a-11ea-9b61-f99db7eb330f.png)

Plex (Not working as intended, when show directory is named `Mirai no Mirai`):
![image](https://user-images.githubusercontent.com/41764397/72864896-56147480-3c9b-11ea-8b57-fd45354357f7.png)

### Logfile
Fresh Log File, where I change the name of the directory to `Mirai no Mirai`, rescan the library and extras disappear, then rename the directory to `Mirai`, rescan the library and extras are picked up by a metadata refresh:
[com.plexapp.agents.localtvextras.log](https://github.com/contrary-cat/LocalTVExtras.bundle/files/4095196/com.plexapp.agents.localtvextras.log)

**Comment by contrary-cat** [comment]
This problem is caused because the agent is really designed to work for the standard Plex scanners, and not any 3rd party ones.

When your directory name is "Mirai no Mirai" it is exactly the same text as the "episode" filename - in that case, the agent assumes that it is in a specific episode subfolder. This means that the assumed show folder that it searches in is actually your anime directory and not the real show folder.

If your episode was named "Mirai no Mirai - S01E01", then the agent would work properly. In fact any difference between the names of the folder and the file should allow for it to work. 

At the moment, the extras you have are being added - it's just that they are attached to the episode instead of the show. So if you switch the "Assign Extras to Episodes, Seasons or Shows based on folder structure" agent setting to false, then the extras would show up (although the agent would still misread the folder structure).

If you want to edit your own copy of the agent to remove the episode name = directory name checks, instead of changing the file or folder names, then I think commenting out or removing lines 164 to 167 should do it.

**Comment by mikansoro** [comment]
Gotcha. Thought it could've been a bug. I can work around the check behavior for my needs and if it eventually becomes an issue for me, I'll remove the directory checks myself.

Thanks.
